# Generated by Django 4.0.1 on 2022-05-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_created_alter_blog_slug_alter_blog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], max_length=1, verbose_name='وضعیت مقاله'),
        ),
    ]
